title: Welcome to my data science portfolio
description 1: ABOUT ME
description 2: Hello! I'm Anietie Etuk 🤓, a data analyst, educator, and consultant with a passion for turning data into actionable insights. With experience across sales, operations, finance, and customer service, I help businesses solve challenges and unlock growth.
logo: WhatsApp Image 2025-01-25 at 9.46.25 PM.jpeg
theme: jekyll-theme-minimal
